//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Yara.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.Yara.NET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rule silent_banker : banker
        ///{
        ///    meta:
        ///        description = &quot;This is just an example&quot;
        ///        thread_level = 3
        ///        in_the_wild = true
        ///
        ///    strings:
        ///        $a = {6A 40 68 00 30 00 00 6A 14 8D 91}
        ///        $b = {8D 4D B0 2B C1 83 C0 27 99 6A 4E 59 F7 F9}
        ///        $c = &quot;UVODFRYSIHLNWPEJXQZAKCBGMT&quot;
        ///
        ///    condition:
        ///        $a or $b or $c
        /////} commented end bracket. Should fail Yara compile.
        /// </summary>
        internal static string FaultyRule {
            get {
                return ResourceManager.GetString("FaultyRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rule silent_banker : banker
        ///{
        ///    meta:
        ///        description = &quot;This is just an example&quot;
        ///        thread_level = 3
        ///        in_the_wild = true
        ///
        ///    strings:
        ///        $a = {4D 59 54 45 53 54 53 54 52 49 4E 47} //MYTESTSTRING
        ///        $b = {53 6f 4d 65 20 52 61 4e 64 4f 6d 20 54 65 58 74} //SoMe RaNdOm TeXt
        ///        $c = &quot;UVODFRYSIHLNWPEJXQZAKCBGMT&quot;
        ///
        ///    condition:
        ///        $a or $b or $c
        ///}.
        /// </summary>
        internal static string TestRule1 {
            get {
                return ResourceManager.GetString("TestRule1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MYTESTSTRING
        ///
        ///SoMe RaNdOm TeXt
        ///
        ///UVODFRYSIHLNWPEJXQZAKCBGMT
        ///UVODFRYSIHLNWPEJXQZAKCBGMT
        ///UVODFRYSIHLNWPEJXQZAKCBGMT.
        /// </summary>
        internal static string TestRule1Data {
            get {
                return ResourceManager.GetString("TestRule1Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rule MyHashYaraRule
        ///{
        ///	strings:
        ///		$a = &quot;test&quot;
        ///	condition:
        ///		$a and not hash.md5(0,filesize) == &quot;20cdf36e37b4fd0144afe1aaa8537f34&quot;
        ///}.
        /// </summary>
        internal static string TestRuleHash {
            get {
                return ResourceManager.GetString("TestRuleHash", resourceCulture);
            }
        }
    }
}
